# These nixos configs are meant to be used with a small wrapper script: nx,
# which checks a few things and sets some environment variables.
{ ... }:
if builtins.getEnv "_IN_NX" != "true" then throw "Must be run by 'nx'" else
let
  host = builtins.getEnv "HOSTNAME";
in
{
  # This root module is a tiny module that just imports a few others.
  imports = [
    # All machines get common.nix
    ./common.nix
    # The hardware directory contains the hardware-configuration.nix files as
    # generated by the installer. Just move them in here, named by the hostname.
    (./. + "/hardware/${host}.nix")
    # Host-specific configs go in a file named by the hostname.
    (./. + "/${host}.nix")
  ];
}
